### ISSUE TITLE
Change Hardcasting bar color when Devouring Plague is usable

### ISSUE THREAD

**Issue by Twintop** [Twintop/TwintopInsanityBar#206]
Add another bar color option to mirror "Insanity when you can cast Devouring Plague", but to instead change the color of the Hardcasted incoming insanity bar instead.

Make this the same color as the base "hardcast spells" by default but independently changeable.

Requested by Stopskii on Discord.

**Comment by stopskii** [comment]
In Priest.lua I suggest altering line 4233 so that 'currentInsanity' is instead 'castingBarValue'.
This way the insanity casting bar changes color if devouring plague will be cast-able after the current cast is complete.
This will make it slightly functionally different than the already implemented "insanity when you can cast Devouring Plague", as currently these two are both using the current insanity to determine when to alter the color, but I feel altering the hard cast incoming insanity color code to account for whether DP is castable after finishing that current hard cast makes more sense.

**Comment by Twintop** [comment]
I've spun this out in to it's own issue (#220) for tracking. This might end up being something tackled when I address some combination of #152 and #163. TBD.
