### ISSUE TITLE
Auspicius Spirits tracker doesn't work

### ISSUE THREAD

**Issue by R1PLI** [Twintop/TwintopInsanityBar#293]
Hi, i'd like to report that those options, '$asInsanity' and '$asCount', doesn't work.

![image](https://user-images.githubusercontent.com/14961671/224558019-5e84bcbc-43b4-41c6-b425-724c7c432165.png)

**Comment by R1PLI** [comment]
Closed as this one should be expected from Blizzard's end

**Comment by Twintop** [comment]
Hey there, just to close the loop on this one with some context:

Blizzard broke Auspicious Spirits generation of Insanity sometime between 10.0.0 and 10.0.5. Instead of generating Insanity on impact (the behavior they had had since added in MoP), the extra Insanity was being generated on spawn. I made a change in #272 to account for this and added #273 to restore it when/if it got fixed.

These variables were still working, it's just that they always reported 0 Auspicious Spirits in flight and 0 Insanity incoming from them. It is worth noting that the first is *not* Shadowy Apparitions in flight, even though the argument could be made that this should be trackable as well.

With 10.0.7 (and the Bar's 10.0.7.0-release) this behavior has largely been restored by Blizzard and will be trackable properly again.

Interesting side note/dive down the rabbit hole: Blizzard changed the way SA (and as a result, AS) work in 10.0.7. Previously, each Shadowy Apparition had it's own `SPELL_CAST_SUCCESS` event that told you what target it was flying towards. This is no longer the case, instead being replaced by a single `SPELL_CAST_SUCCESS` without a target that represents the spawn of all of the Shadowy Apparitions. I had to make some tweaks under the hood to account for this and am expecting (unfortunately) the possibility of some inaccurate AS counts if Vampiric Touch expires on a target at the same time as the spawning of SAs occurs.

Additionally, In 10.1.0 there are bugs around SAs not granting Insanity generation if they impact with a target that has dropped combat with you (e.g. training dummy, Shadowmelded target).

---

Thanks for reporting this @R1PLI , even if there isn't anything actionable about it. I always prefer it when people bring things to my attention as a possible bug/issue that needs to be sorted out instead of leaving it unreported!
