### ISSUE TITLE
No Demon Hunter Options - AirHorn blasting at resource capping

### ISSUE THREAD

**Issue by Shielumad** [Twintop/TwintopInsanityBar#296]
With the release of 10.0.7, I started getting blasted with an airhorn when resource capped, instead of the usual bell that was set. When I went into option to look at what was going on, I couldn't access any of the options. The resource bar works fine for my Shadow Priest though.

What I've tried:
- Uninstalling/reinstalling
- Changing to beta version and back
- Disabling all other addons

None have worked, current workaround was to delete the airhorn file.

![image](https://user-images.githubusercontent.com/128939410/227745846-e4e16284-f2e6-455a-a18c-06b5fa210954.png)

**Comment by Twintop** [comment]
Hey @Shielumad, thanks for reporting this. I think there are two separate issues occuring here:

The options menu was a mistake on my side while trying to retrofit how those options subsections get added. I unfortunately missed the Demon Hunter one when doing that work. Apologies! This is fixed in 10.0.7.1-release which should be available on Curse/Wago/WoWI in a few minutes.

For the sound changing from a bell sound to the airhorn, this is likely because another addon of yours was providing the bell sound. If that other addon wasn't loading for whatever reason (or removed the sound as an option), then the bell sound wouldn't show up as a viable option and the Resource Bar would fall back to the default (airhorn) sound instead. When this happens, the Resource Bar prints a message out in to chat, unfortunately it can be easily missed. Now that you can access the options panel again you should be able to change it back.

**Comment by Shielumad** [comment]
Champion. Thanks for fixing that.
